[tool.poetry]
name = "lc-classifier"
version = "23.12.26a28"
description = "Lightcurve classifiers and feature computation"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "lc_classifier"}]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
astropy = "^4.0"
imbalanced-learn = "^0.7"
numba = "^0.51"
numpy = "^1.16"
pyarrow = "*"
requests = "^2.24"
scipy = "^1.4"
scikit-learn = "^1.2"
statsmodels = "*"
tensorflow = "^2.3"
pandas = "2.0.1"
wget = "^3.2"
celerite2 = "^0.1"
extinction = "*"
jax = {version = "*", extras = ["cpu"]}
mhps = {path = "../mhps", develop = true}
P4J = {path = "../P4J", develop = true}
tensorflow-io-gcs-filesystem = { version = "~0.33" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
