language: python

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install coverage

script:
  - coverage run --source db_plugins -m unittest tests/run_tests.py

after_success:
  - coverage report