language: python

jobs:
  include:
    - os: linux
      python: 3.6
      env: TOXENV=py36
    - os: linux
      python: 3.8
      env: TOXENV=py38
    - os: osx
      language: generic
      env: TOXENV=py36
    - os: osx
      language: generic
      env: TOXENV=py38

install:
  - ./.travis/install.sh
  - pip install numpy==1.18.5 pandas
  - pip install -r requirements.txt
  - pip install -e .

script:
  - python -m unittest discover