language: python

before_install:
  - openssl aes-256-cbc -K $encrypted_3500de29b3e0_key -iv $encrypted_3500de29b3e0_iv -in turb\
ofats_travis_public.enc -out turbofats_travis_public -d
  - chmod 600 turbofats_travis_public
  - eval $(ssh-agent -s)
  - ssh-add turbofats_travis_public

install:
  - git clone --branch staging -depth=1 git@github.com:alercebroker/stamp_classifier.git
  - mv stamp_classifier ..

before_script:
  - cd tests
  - docker-compose up -d

script:
  - docker-compose -f docker-compose-run-test.yml run early_classification_step

after_script:
  - docker-compose down