language: python

before_install:
  - openssl aes-256-cbc -K $encrypted_3c492a190922_key -iv $encrypted_3c492a190922_iv -in stamp_classifier_travis.enc -out stamp_classifier_travis -d
  - chmod 600 stamp_classifier_travis
  - eval $(ssh-agent -s)
  - ssh-add stamp_classifier_travis

install:
  - git clone --branch staging -depth=1 git@github.com:alercebroker/stamp_classifier.git
  - mv stamp_classifier ..

before_script:
  - cd tests
  - docker-compose up -d

script:
  - docker-compose -f docker-compose-run-test.yml run early_classification_step

after_script:
  - docker-compose down