language: python

jobs:
  include:
    - name: "Python 3.6 on Xenial Linux"
      os: linux
      python: 3.6
    - name: "Python 3.8 on Xenial Linux"
      os: linux
      python: 3.8
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell
      

install:
  - pip3 install numpy==1.18.5 pandas
  - pip3 install -r requirements.txt
  - pip3 install -e .

script:
  - python3 -m unittest discover