language: python

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install coverage

script:
  - coverage run --source db_plugins -m pytest

after_success: bash <(curl -s https://codecov.io/bash)
