language: python
python:
  - "3.6"      
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install numpy Cython
  - pip install -r requirements.txt
  - pip install -e .

script:
  - cd turbofats/tests && python tests_ignacio.py
