version: "3"
services:
  features:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "always"
    env_file:
      - db_settings.env
      - es_settings.env
    environment:
      - CONSUMER_TOPICS=correction-test
      - CONSUMER_SERVER=kafka.alerce.online:9092
      - CONSUMER_GROUP_ID=test-features
      - PRODUCER_TOPIC=features-test
      - PRODUCER_SERVER=kafka.alerce.online:9092