apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "early-classifier.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  consumer-topics: {{ .Values.configmap.consumerTopics }}
  consumer-server: {{ .Values.configmap.consumerServer }}
  consumer-group: {{ .Values.configmap.consumerGroup }}
  topic-strategy-format: "{{ .Values.configmap.topicStrategy.format }}"
  producer-server: {{ .Values.configmap.producerServer }}
  producer-topic-format: {{ .Values.configmap.producerTopicFormat }}
  producer-date-format: "{{ .Values.configmap.producerDateFormat }}"
  producer-change-hour: "{{ .Values.configmap.producerChangeHour }}"
  metrics-server: {{ .Values.configmap.metricsServer }}
  metrics-topic: {{ .Values.configmap.metricsTopic }}
  classifier-version: {{ .Values.configmap.classifierVersion }}
  producer-schema-path: {{ .Values.configmap.producerSchemaPath }}
  metrics-schema-path: {{ .Values.configmap.metricsSchemaPath }}
  consumer-schema-path: {{ .Values.configmap.consumerSchemaPath }}
  