# Default values for scribe.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/alercebroker/alercescribe
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespace: scribe-step

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
          - matchExpressions:
            - key: eks.amazonaws.com/nodegroup
              operator: In
              values: []

envVariables:
  - name: CONFIG_FROM_YAML
    value: "yes"
  ## - name: METRICS_SOURCE
  ##   value: {{ .Release.Name }}
  ## - name: METRICS_SURVEY
  ##   value: ATLAS

configYaml:
  enabled: true
  DB_TYPE: ""
  DB_SECRET_NAME: ""
  CONSUMER_CONFIG:
    CLASS: "apf.consumers.KafkaConsumer"
    SCHEMA_PATH: "/schemas/scribe_step/scribe.avsc"
    PARAMS:
      bootstrap.servers: ""
      group.id: ""
      auto.offset.reset: "beginning"
      security.protocol: "SASL_SSL"
      sasl.mechanism: "SCRAM-SHA-512"
      sasl.username: ""
      sasl.password: ""
    TOPICS: []
    NUM_MESSAGES: 50
    TIMEOUT: 10
  METRICS_CONFIG:
    CLASS: "apf.metrics.KafkaMetricsProducer"
    SCHEMA_PATH: "/schemas/scribe_step/metrics.json"
    TOPIC: "metrics"
    PARAMS:
      bootstrap.servers: ""
      security.protocol: "SASL_SSL"
      sasl.mechanism: "SCRAM-SHA-512"
      sasl.username: ""
      sasl.password: ""
  FEATURE_FLAGS:
    PROMETHEUS: false
  USE_PROFILING: true
  PYROSCOPE_SERVER: "http://pyroscope.pyroscope:4040"
