name: Tests_feature_step

on:
  pull_request:
    paths:
      - 'feature_step/**'
    branches:
      - main

jobs:
  lint:
    uses: alercebroker/workflow-templates/.github/workflows/lint.yml@main
    with:
      sources-folder: 'feature_step/feature_step/'
  unittest:
    uses: alercebroker/workflow-templates/.github/workflows/pip-tests.yml@main
    with:
      python-version: '3.10'
      sources-folder: 'feature_step/feature_step/'
      test-folder: 'feature_step/tests/unittest'
      test-dependencies: 'pytest pytest-cov'
      requirements-file: 'feature_step/requirements.txt'
      codecov-flags: ''  # Do not upload
      test-command: 'python -m pytest -x feature_step/tests/unittest --cov feature_step/features--cov-report xml'
  integration:
    uses: alercebroker/workflow-templates/.github/workflows/pip-tests.yml@main
    with:
      python-version: '3.10'
      sources-folder: 'feature_step/alerce-reflector-step/'
      test-folder: 'feature_step/tests/integration'
      test-dependencies: 'pytest pytest-docker'
      requirements-file: 'feature_step/requirements.txt'
      codecov-flags: ''  # Do not upload
      test-command: 'python -m pytest -x feature_step/tests/integration'