# Default values for step_starter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: prv-candidates

image:
  repository: ghcr.io/alercebroker/prv_candidates_step
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets:
  - name: "image-pull-access"
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: nodegroup
              operator: In
              ## Override this value with the NodeGroup tag accordingly
              values: []

imageCredentials:
  registry: ""
  username: ""
  password: ""
  email: ""

envVariables:
  - name: CONFIG_FROM_YAML
    value: "yes"
  ## - name: METRICS_SOURCE
  ##   value: {{ .Release.Name }}
  ## - name: METRICS_SURVEY
  ##   value: ATLAS

configYaml:
  enabled: true
  CONSUMER_CONFIG:
    CLASS: "apf.consumers.KafkaConsumer"
    SCHEMA_PATH: "/schemas/sorting_hat_step/output.avsc"
    PARAMS:
      bootstrap.servers: ""
      group.id: "prv-candidates-step"
      auto.offset.reset: "beginning"
      enable.partition.eof: false
      security.protocol: "SASL_SSL"
      sasl.mechanism: "SCRAM-SHA-512"
      sasl.username: ""
      sasl.password: ""
    TOPICS: ["^sorting-hat.*"]
    consume.messages: 100
    consume.timeout: 10
  PRODUCER_CONFIG:
    CLASS: "apf.producers.KafkaProducer"
    PARAMS:
      bootstrap.servers: ""
      message.max.bytes: 6291456
      security.protocol: "SASL_SSL"
      sasl.mechanism: "SCRAM-SHA-512"
      sasl.username: ""
      sasl.password: ""
    TOPIC: "prv-candidates"
    SCHEMA_PATH: "/schemas/prv_candidate_step/output.avsc"
  SCRIBE_PRODUCER_CONFIG:
    CLASS: "apf.producers.KafkaProducer"
    PARAMS:
      bootstrap.servers: ""
      security.protocol: "SASL_SSL"
      sasl.mechanism: "SCRAM-SHA-512"
      sasl.username: ""
      sasl.password: ""
    TOPIC: "w_non_detections"
    SCHEMA_PATH: "/schemas/scribe_step/scribe.avsc"
  METRICS_CONFIG:
    CLASS: "apf.metrics.KafkaMetricsProducer"
    EXTRA_METRICS:
      - key: candid
      - key: oid
      - key: aid
    PARAMS:
      PARAMS:
        bootstrap.servers: ""
        security.protocol: "SASL_SSL"
        sasl.mechanism: "SCRAM-SHA-512"
        sasl.username: ""
        sasl.password: ""
      TOPIC: "metrics"
      SCHEMA_PATH: "/schemas/prv_candidate_step/metrics.json"
  LOGGING_DEBUG: false
  USE_PROMETHEUS: false
  PYROSCOPE_SERVER: "http://pyroscope.pyroscope:4040"
  USE_PROFILING: false
