from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    LongType,
    DoubleType,
    ArrayType,
)


schema_avros = StructType(
    [
        StructField("schemavsn", StringType(), True),
        StructField("publisher", StringType(), True),
        StructField("objectId", StringType(), True),
        StructField(
            "candidate",
            StructType(
                [
                    StructField("jd", DoubleType(), True),
                    StructField("fid", LongType(), True),
                    StructField("pid", LongType(), True),
                    StructField("diffmaglim", DoubleType(), True),
                    StructField("pdiffimfilename", StringType(), True),
                    StructField("programpi", StringType(), True),
                    StructField("programid", LongType(), True),
                    StructField("candid", LongType(), True),
                    StructField("isdiffpos", StringType(), True),
                    StructField("tblid", LongType(), True),
                    StructField("nid", LongType(), True),
                    StructField("rcid", LongType(), True),
                    StructField("field", LongType(), True),
                    StructField("xpos", DoubleType(), True),
                    StructField("ypos", DoubleType(), True),
                    StructField("ra", DoubleType(), True),
                    StructField("dec", DoubleType(), True),
                    StructField("magpsf", DoubleType(), True),
                    StructField("sigmapsf", DoubleType(), True),
                    StructField("chipsf", DoubleType(), True),
                    StructField("magap", DoubleType(), True),
                    StructField("sigmagap", DoubleType(), True),
                    StructField("distnr", DoubleType(), True),
                    StructField("magnr", DoubleType(), True),
                    StructField("sigmagnr", DoubleType(), True),
                    StructField("chinr", DoubleType(), True),
                    StructField("sharpnr", DoubleType(), True),
                    StructField("sky", DoubleType(), True),
                    StructField("magdiff", DoubleType(), True),
                    StructField("fwhm", DoubleType(), True),
                    StructField("classtar", DoubleType(), True),
                    StructField("mindtoedge", DoubleType(), True),
                    StructField("magfromlim", DoubleType(), True),
                    StructField("seeratio", DoubleType(), True),
                    StructField("aimage", DoubleType(), True),
                    StructField("bimage", DoubleType(), True),
                    StructField("aimagerat", DoubleType(), True),
                    StructField("bimagerat", DoubleType(), True),
                    StructField("elong", DoubleType(), True),
                    StructField("nneg", LongType(), True),
                    StructField("nbad", LongType(), True),
                    StructField("rb", DoubleType(), True),
                    StructField("ssdistnr", DoubleType(), True),
                    StructField("ssmagnr", DoubleType(), True),
                    StructField("ssnamenr", StringType(), True),
                    StructField("sumrat", DoubleType(), True),
                    StructField("magapbig", DoubleType(), True),
                    StructField("sigmagapbig", DoubleType(), True),
                    StructField("ranr", DoubleType(), True),
                    StructField("decnr", DoubleType(), True),
                    StructField("sgmag1", DoubleType(), True),
                    StructField("srmag1", DoubleType(), True),
                    StructField("simag1", DoubleType(), True),
                    StructField("szmag1", DoubleType(), True),
                    StructField("sgscore1", DoubleType(), True),
                    StructField("distpsnr1", DoubleType(), True),
                    StructField("ndethist", LongType(), True),
                    StructField("ncovhist", LongType(), True),
                    StructField("jdstarthist", DoubleType(), True),
                    StructField("jdendhist", DoubleType(), True),
                    StructField("scorr", DoubleType(), True),
                    StructField("tooflag", LongType(), True),
                    StructField("objectidps1", LongType(), True),
                    StructField("objectidps2", LongType(), True),
                    StructField("sgmag2", DoubleType(), True),
                    StructField("srmag2", DoubleType(), True),
                    StructField("simag2", DoubleType(), True),
                    StructField("szmag2", DoubleType(), True),
                    StructField("sgscore2", DoubleType(), True),
                    StructField("distpsnr2", DoubleType(), True),
                    StructField("objectidps3", LongType(), True),
                    StructField("sgmag3", DoubleType(), True),
                    StructField("srmag3", DoubleType(), True),
                    StructField("simag3", DoubleType(), True),
                    StructField("szmag3", DoubleType(), True),
                    StructField("sgscore3", DoubleType(), True),
                    StructField("distpsnr3", DoubleType(), True),
                    StructField("nmtchps", LongType(), True),
                    StructField("rfid", LongType(), True),
                    StructField("jdstartref", DoubleType(), True),
                    StructField("jdendref", DoubleType(), True),
                    StructField("nframesref", LongType(), True),
                    StructField("rbversion", StringType(), True),
                    StructField("dsnrms", DoubleType(), True),
                    StructField("ssnrms", DoubleType(), True),
                    StructField("dsdiff", DoubleType(), True),
                    StructField("magzpsci", DoubleType(), True),
                    StructField("magzpsciunc", DoubleType(), True),
                    StructField("magzpscirms", DoubleType(), True),
                    StructField("nmatches", LongType(), True),
                    StructField("clrcoeff", DoubleType(), True),
                    StructField("clrcounc", DoubleType(), True),
                    StructField("zpclrcov", DoubleType(), True),
                    StructField("zpmed", DoubleType(), True),
                    StructField("clrmed", DoubleType(), True),
                    StructField("clrrms", DoubleType(), True),
                    StructField("neargaia", DoubleType(), True),
                    StructField("neargaiabright", DoubleType(), True),
                    StructField("maggaia", DoubleType(), True),
                    StructField("maggaiabright", DoubleType(), True),
                    StructField("exptime", DoubleType(), True),
                    StructField("drb", DoubleType(), True),
                    StructField("drbversion", StringType(), True),
                ]
            ),
            True,
        ),
        StructField(
            "prv_candidates",
            ArrayType(
                StructType(
                    [
                        StructField("jd", DoubleType(), True),
                        StructField("fid", LongType(), True),
                        StructField("pid", LongType(), True),
                        StructField("diffmaglim", DoubleType(), True),
                        StructField("pdiffimfilename", StringType(), True),
                        StructField("programpi", StringType(), True),
                        StructField("programid", LongType(), True),
                        StructField("candid", LongType(), True),
                        StructField("isdiffpos", StringType(), True),
                        StructField("tblid", LongType(), True),
                        StructField("nid", LongType(), True),
                        StructField("rcid", LongType(), True),
                        StructField("field", LongType(), True),
                        StructField("xpos", DoubleType(), True),
                        StructField("ypos", DoubleType(), True),
                        StructField("ra", DoubleType(), True),
                        StructField("dec", DoubleType(), True),
                        StructField("magpsf", DoubleType(), True),
                        StructField("sigmapsf", DoubleType(), True),
                        StructField("chipsf", DoubleType(), True),
                        StructField("magap", DoubleType(), True),
                        StructField("sigmagap", DoubleType(), True),
                        StructField("distnr", DoubleType(), True),
                        StructField("magnr", DoubleType(), True),
                        StructField("sigmagnr", DoubleType(), True),
                        StructField("chinr", DoubleType(), True),
                        StructField("sharpnr", DoubleType(), True),
                        StructField("sky", DoubleType(), True),
                        StructField("magdiff", DoubleType(), True),
                        StructField("fwhm", DoubleType(), True),
                        StructField("classtar", DoubleType(), True),
                        StructField("mindtoedge", DoubleType(), True),
                        StructField("magfromlim", DoubleType(), True),
                        StructField("seeratio", DoubleType(), True),
                        StructField("aimage", DoubleType(), True),
                        StructField("bimage", DoubleType(), True),
                        StructField("aimagerat", DoubleType(), True),
                        StructField("bimagerat", DoubleType(), True),
                        StructField("elong", DoubleType(), True),
                        StructField("nneg", LongType(), True),
                        StructField("nbad", LongType(), True),
                        StructField("rb", DoubleType(), True),
                        StructField("ssdistnr", DoubleType(), nullable=True),
                        StructField("ssmagnr", DoubleType(), True),
                        StructField("ssnamenr", StringType(), True),
                        StructField("sumrat", DoubleType(), True),
                        StructField("magapbig", DoubleType(), True),
                        StructField("sigmagapbig", DoubleType(), True),
                        StructField("ranr", DoubleType(), True),
                        StructField("decnr", DoubleType(), True),
                        StructField("scorr", DoubleType(), True),
                        StructField("magzpsci", DoubleType(), True),
                        StructField("magzpsciunc", DoubleType(), True),
                        StructField("magzpscirms", DoubleType(), True),
                        StructField("clrcoeff", DoubleType(), True),
                        StructField("clrcounc", DoubleType(), True),
                        StructField("rbversion", StringType(), True),
                    ]
                ),
                True,
            ),
            True,
        ),
        StructField(
            "fp_hists",
            ArrayType(
                StructType(
                    [
                        StructField("field", LongType(), True),
                        StructField("rcid", LongType(), True),
                        StructField("fid", LongType(), True),
                        StructField("pid", LongType(), True),
                        StructField("rfid", LongType(), True),
                        StructField("sciinpseeing", DoubleType(), True),
                        StructField("scibckgnd", DoubleType(), True),
                        StructField("scisigpix", DoubleType(), True),
                        StructField("magzpsci", DoubleType(), True),
                        StructField("magzpsciunc", DoubleType(), True),
                        StructField("magzpscirms", DoubleType(), True),
                        StructField("clrcoeff", DoubleType(), True),
                        StructField("clrcounc", DoubleType(), True),
                        StructField("exptime", DoubleType(), True),
                        StructField("adpctdif1", DoubleType(), True),
                        StructField("adpctdif2", DoubleType(), True),
                        StructField("diffmaglim", DoubleType(), True),
                        StructField("programid", LongType(), True),
                        StructField("jd", DoubleType(), True),
                        StructField("forcediffimflux", DoubleType(), True),
                        StructField("forcediffimfluxunc", DoubleType(), True),
                        StructField("procstatus", StringType(), True),
                        StructField("distnr", DoubleType(), True),
                        StructField("ranr", DoubleType(), True),
                        StructField("decnr", DoubleType(), True),
                        StructField("magnr", DoubleType(), True),
                        StructField("sigmagnr", DoubleType(), True),
                        StructField("chinr", DoubleType(), True),
                        StructField("sharpnr", DoubleType(), True),
                    ]
                ),
                True,
            ),
            True,
        ),
    ]
)
