name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'stamp_classifier_step/**'
      - '!stamp_classifier_step/README.md'

jobs:
  stamp_classifier_step_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
      base-folder: 'stamp_classifier_step'
      sources-folder: 'stamp_classifier_step'

  stamp_classifier_step_unittest_atlas:
    uses: ./.github/workflows/pip-tests-template.yaml
    with:
      base-folder: 'stamp_classifier_step'
      python-version: '3.8'
      sources-folder: 'stamp_classifier_step'
      requirements-file: 'requirements.txt'
      test-folder: 'tests/unittest'
      test-dependencies: 'pytest pytest-cov'
      test-command: 'python -m pytest -x tests/unittests --cov stamp_classifier_step --cov-report xml'
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'

  stamp_classifier_step_unittest_ztf:
    uses: ./.github/workflows/pip-tests-template.yaml
    with:
      base-folder: 'stamp_classifier_step'
      python-version: '3.7'
      sources-folder: 'stamp_classifier_step'
      requirements-file: 'requirements.txt -r model/requirements.txt'
      test-folder: 'tests/unittest'
      test-dependencies: 'pytest pytest-cov'
      test-command: 'python -m pytest -x tests/unittests --cov stamp_classifier_step --cov-report xml'
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}

  stamp_classifier_step_integration:
    uses: ./.github/workflows/pip-tests-template.yaml
    with:
      base-folder: 'stamp_classifier_step'
      python-version: '3.8'
      sources-folder: 'stamp_classifier_step'
      requirements-file: 'requirements.txt'
      test-folder: 'tests/integration'
      test-dependencies: 'pytest pytest-docker'
      test-command: 'python -m pytest -x tests/integration'
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
