apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prv-candidates.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    {{- toYaml .Values.configYaml | nindent 4 }}
