atat:
  ft:
    embedding_size: 128
    embedding_size_sub: 256
    num_heads_tab: 4
    num_encoders_tab: 3

  lc:
    input_size: 1
    embedding_size: 192
    embedding_size_sub: 384
    num_heads: 4
    num_encoders: 3
    Tmax: 1500.0
    num_harmonics: 64
    pe_type: tm

  enc:
    encoder_type: Linear
    encoder_type_tab: Linear
    max_pool_kernel: 5
    cnn_kernel: 5

lc_ssl_projection:
  projection_size: 48
  l2_norm: False

ft_ssl_projection:
  projection_size: 48
  l2_norm: False

alignment_projection:
  projection_size: 128
  l2_norm: True
