name: integration_test

on:
  pull_request:
    paths:
      - 'alert_archiving_step/**'
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy Cython pytest-docker
          if [ -f alert_archiving_step/requirements.txt ]; then pip install -r alert_archiving_step/requirements.txt; fi
      - name: Test with pytest
        run: |
          python -m pytest -x -s alert_archiving_step/tests/integration/
