name: Tests_alerce-reflector-step

on:
  pull_request:
    paths:
      - 'alerce-reflector-step/**'
    branches:
      - main

jobs:
  lint:
    uses: alercebroker/workflow-templates/.github/workflows/lint.yml@main
    with:
      sources-folder: 'alerce-reflector-step/alerce-reflector-step/'
  unittest:
    uses: alercebroker/workflow-templates/.github/workflows/pip-tests.yml@main
    with:
      python-version: '3.7'
      sources-folder: 'alerce-reflector-step/alerce-reflector-step/'
      test-folder: 'alerce-reflector-step/tests/unittest'
      test-dependencies: 'pytest pytest-docker pytest-cov'
      pre-dependencies: 'apf-base==1.0.7'
      test-command: 'python -m pytest -x alerce-reflector-step/tests/unittest --cov alerce-reflector-step/cmirrormaker --cov-report xml'
  integration:
    uses: alercebroker/workflow-templates/.github/workflows/pip-tests.yml@main
    with:
      python-version: '3.7'
      sources-folder: 'alerce-reflector-step/alerce-reflector-step/'
      test-folder: 'alerce-reflector-step/tests/integration'
      test-dependencies: 'pytest pytest-docker pytest-cov'
      pre-dependencies: 'apf-base==1.0.7'
      codecov-flags: ''  # Do not upload
      test-command: 'python -m pytest -x alerce-reflector-step/tests/integration'
