name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'libs/apf/**'
      - '!libs/apf/docs/**'
      - '!libs/apf/README.md'

jobs:
  libs_apf_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
      base-folder: 'libs/apf'
      sources-folder: 'apf'
  libs_apf_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'libs/apf'
      sources-folder: 'apf'
      test-folder: 'tests'
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'

  reflector_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
        python-version: '3.7'
        sources-folder: 'reflector_step'
        test-folder: 'tests/unittest'
        base-folder: 'reflector_step'
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  reflector_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      python-version: '3.7'
      sources-folder: 'reflector_step'
      base-folder: 'reflector_step'
      test-folder: 'tests/integration'
      codecov-flags: ''  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  reflector_step_build:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: "reflector_step"
      build-context: "reflector_step"
      step-name: "reflector_step"
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'

  sorting_hat_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'sorting_hat_step'
      python-version: '3.8'
      sources-folder: 'sorting_hat_step'
      test-folder: 'tests/unittest'
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  sorting_hat_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'sorting_hat_step'
      python-version: '3.8'
      sources-folder: 'sorting_hat_step'
      test-folder: 'tests/integration'
      codecov-flags: ''  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  sorting_hat_step_build:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: "sorting_hat_step"
      build-context: "."
      step-name: "sorting_hat_step"
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'

  prv_candidates_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'prv_candidates_step'
      python-version: "3.8"
      test-folder: "tests/unit"
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  prv_candidates_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'prv_candidates_step'
      python-version: '3.8'
      sources-folder: 'prv_candidates_step'
      test-folder: 'tests/integration'
      codecov-flags: ''  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  prv_candidates_step_build:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: "prv_candidates_step"
      build-context: "."
      step-name: "prv_candidates_step"
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'

  lightcurve_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'lightcurve-step'
      python-version: "3.9"
      test-folder: "tests/unittest"
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  lightcurve_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'lightcurve-step'
      python-version: "3.9"
      test-folder: "tests/integration"
      codecov-flags: "" # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  lightcurve_step_build:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: "lightcurve-step"
      build-context: "."
      step-name: "lightcurve-step"
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'

  correction_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'correction_step'
      sources-folder: 'correction'
      test-folder: 'tests/unittests'
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  correction_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'correction_step'
      sources-folder: 'correction'
      test-folder: 'tests/integration'
      codecov-flags: ''  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  correction_step_build:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: "correction_step"
      build-context: "."
      step-name: "correction_step"
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'

  xmatch_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'xmatch_step'
      python-version: "3.7"
      test-folder: "tests/unittest"
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  xmatch_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'xmatch_step'
      python-version: '3.7'
      sources-folder: 'xmatch_step'
      test-folder: 'tests/integration'
      codecov-flags: ''  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  xmatch_step_build:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: "xmatch_step"
      build-context: "."
      step-name: "xmatch_step"
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'

  lc_classification_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'lc_classification_step'
      python-version: '3.8'
      poetry-install: "--with ztf --with elasticc"
      test-folder: "tests/unit"
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
      TEST_BALTO_MODEL_PATH: "${{ secrets.TEST_BALTO_MODEL_PATH }}"
      TEST_BALTO_QUANTILES_PATH: "${{ secrets.TEST_BALTO_QUANTILES_PATH }}"
      TEST_MESSI_MODEL_PATH: "${{ secrets.TEST_MESSI_MODEL_PATH }}"
      TEST_MESSI_HEADER_QUANTILES_PATH: "${{ secrets.TEST_MESSI_HEADER_QUANTILES_PATH }}"
      TEST_MESSI_FEATURE_QUANTILES_PATH: "${{ secrets.TEST_MESSI_FEATURE_QUANTILES_PATH }}"
      TEST_TORETTO_MODEL_PATH: "${{ secrets.TEST_TORETTO_MODEL_PATH }}"
      TEST_BARNEY_MODEL_PATH: "${{ secrets.TEST_BARNEY_MODEL_PATH }}"
      TEST_NEW_BARNEY_MODEL_PATH: "${{ secrets.TEST_NEW_BARNEY_MODEL_PATH }}"
      TEST_MLP_MODEL_PATH: "${{ secrets.TEST_MLP_MODEL_PATH }}"
  lc_classification_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'lc_classification_step'
      python-version: '3.8'
      codecov-flags: ''  # Do not upload
      poetry-install: "--with ztf --with elasticc"
      test-folder: "tests/integration"
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
      TEST_BALTO_MODEL_PATH: "${{ secrets.TEST_BALTO_MODEL_PATH }}"
      TEST_BALTO_QUANTILES_PATH: "${{ secrets.TEST_BALTO_QUANTILES_PATH }}"
      TEST_MESSI_MODEL_PATH: "${{ secrets.TEST_MESSI_MODEL_PATH }}"
      TEST_MESSI_HEADER_QUANTILES_PATH: "${{ secrets.TEST_MESSI_HEADER_QUANTILES_PATH }}"
      TEST_MESSI_FEATURE_QUANTILES_PATH: "${{ secrets.TEST_MESSI_FEATURE_QUANTILES_PATH }}"
      TEST_TORETTO_MODEL_PATH: "${{ secrets.TEST_TORETTO_MODEL_PATH }}"
      TEST_BARNEY_MODEL_PATH: "${{ secrets.TEST_BARNEY_MODEL_PATH }}"
      TEST_NEW_BARNEY_MODEL_PATH: "${{ secrets.TEST_NEW_BARNEY_MODEL_PATH }}"
      TEST_MLP_MODEL_PATH: "${{ secrets.TEST_MLP_MODEL_PATH }}"

  lc_classification_step_build_ztf:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: "lc_classification_step"
      build-context: "."
      step-name: "lc_classification_step_ztf"
      file: "Dockerfile.ztf"
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
  lc_classification_step_build_balto:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: "lc_classification_step"
      build-context: "."
      step-name: "lc_classification_step_balto"
      file: "Dockerfile.balto"
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
  lc_classification_step_build_messi:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: "lc_classification_step"
      build-context: "."
      step-name: "lc_classification_step_messi"
      file: "Dockerfile.messi"
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
  lc_classification_step_build_barney:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: "lc_classification_step"
      build-context: "."
      step-name: "lc_classification_step-barney"
      file: "Dockerfile.barney"
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
  lc_classification_step_build_mlp:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: "lc_classification_step"
      build-context: "."
      step-name: "lc_classification_step-mpl"
      file: "Dockerfile.mlp"
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
  lc_classification_step_build_toretto:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: "lc_classification_step"
      build-context: "."
      step-name: "lc_classification_step-toretto"
      file: "Dockerfile.toretto"
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}

  feature_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      python-version: '3.10'
      base-folder: 'feature_step'
      sources-folder: 'features'
      test-folder: 'tests/unittest'
      codecov-flags: ''  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  feature_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      python-version: '3.10'
      base-folder: 'feature_step'
      sources-folder: 'features/'
      test-folder: 'tests/integration'
      codecov-flags: ''  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  feature_step_build:
    uses: ./.github/workflows/build-template.yaml
    with:
      step-name: feature_step
      step-name-prefix: ""
      base-folder: feature_step
      build-context: "."
      git-ref: ${{ github.ref }}
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
