name: Build Production

on:
  release:
    types:
      - published

jobs:
  alerce_reflector_step_staging:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: alerce_reflector_step
      step-name: alerce_reflector_step
      build-type: production
