name: Build test
on:
  workflow_call:
    inputs:
      base-folder:
        required: false
        type: string
        default: '.'
      file:
        required: false
        type: string
        default: 'Dockerfile'
      step-name:
        required: true
        type: string

jobs:
  build:
    name: Build the image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./${{ inputs.base-folder }}
          file: ./${{ inputs.base-folder }}/${{ inputs.file }}
          push: false
          tags: "ghcr.io/alercebroker/test_${{ inputs.step-name }}:test"
