name: Tests

on:
  push:
    branches:
      - main
env:
  build_type: staging

jobs:
  alerce_reflector_step_staging:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: alerce_reflector_step
      step-name: alerce_reflector_step
      build-type: ${{ env.build_type }}
  correction_step_staging:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: correction_step
      step-name: correction_step
      build-type: ${{ env.build_type }}
