name: Build_template
on:
  workflow_call:
    inputs:
      base-folder:
        required: false
        type: string
        default: '.'
      file:
        required: false
        type: string
        default: 'Dockerfile'
      step-name:
        required: true
        type: string
      build-type:
        required: true
        type: string

jobs:
  get_tags:
    env:
      STEP_NAME: 'monorepo_${{ inputs.step-name }}'
      BUILD_TYPE: ${{ inputs.build-type }}
      POETRY_HOME: /opt/poetry
    name: get tags
    outputs:
      tags: ${{ steps.prep.outputs.tags }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install poetry ${{ matrix.poetry-version }}
        run: |
          pip install --upgrade pip
          pip install poetry
          $POETRY_HOME/bin/poetry --version
      - name: Prepare
        id: prep
        run: |
          if [[ $BUILD_TYPE == production ]]; then
            BUILD_TYPE=latest
          else
            BUILD_TYPE=rc
          fi
          DOCKER_IMAGE=ghcr.io/alercebroker/${STEP_NAME}
          VERSION=$($POETRY_HOME/bin/poetry version --short)
          TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:${BUILD_TYPE}"
          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"

  build_and_push:
    name: Push Docker image to GitHub Packages
    needs: get_tags
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v4
        with:
          context: ./${{ inputs.base-folder }}
          file: ./${{ inputs.base-folder }}/${{ inputs.file }}
          push: true
          tags: ${{needs.get_tags.outputs.tags}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
