name: Build Production V1

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_versions:
    uses: ./.github/workflows/update-versions.yaml
    needs: update_versions
    with:
      build-type: production

  alert_archiving_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: alert_archiving_step
      base-folder: alert_archiving_step
      git_ref: release/v1

  early_classification_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: early_classification_step
      base-folder: early_classification_step
      git_ref: release/v1


  feature_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: feature_step
      step-name-prefix: ""
      base-folder: feature_step
      git_ref: release/v1


  lc_classification_step_ztf_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: lc_classification_step_ztf
      step-name-prefix: ""
      build-context: lc_classification_step
      base-folder: lc_classification_step
      file: Dockerfile-ztf
      git_ref: release/v1

    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}

  s3_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: s3_step
      step-name-prefix: ""
      base-folder: s3_step
      build-context: s3_step
      git_ref: release/v1


  sorting_hat_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: sorting_hat_step
      step-name-prefix: ""
      base-folder: sorting_hat_step
      git_ref: release/v1


  watchlist_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: watchlist_step
      base-folder: watchlist_step
      git_ref: release/v1


  xmatch_step_production:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: production
      step-name: xmatch_step
      base-folder: xmatch_step
      git_ref: release/v1
