name: Build Staging

on:
  push:
    branches:
      - main

jobs:
  update_versions:
    uses: ./.github/workflows/update-versions.yaml
    with:
      build-type: staging

  alert_archiving_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: alert_archiving_step
      base-folder: alert_archiving_step

  correction_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: correction_step
      base-folder: correction_step

  early_classification_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: early_classification_step
      base-folder: early_classification_step

  feature_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: feature_step
      base-folder: feature_step

  lc_classification_step_ztf_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: lc_classification_step_ztf
      base-folder: lc_classification_step
      file: Dockerfile-ztf

  lc_classification_step_balto_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: lc_classification_step_balto
      base-folder: lc_classification_step
      file: Dockerfile-balto

  lc_classification_step_messi_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: lc_classification_step_messi
      base-folder: lc_classification_step
      file: Dockerfile-messi

  lc_classification_step_barney_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: lc_classification_step_barney
      base-folder: lc_classification_step
      file: Dockerfile-barney

  lc_classification_step_toretto_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: lc_classification_step_toretto
      base-folder: lc_classification_step
      file: Dockerfile-toretto

  lightcurve_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: lightcurve_step
      base-folder: lightcurve-step

  magstats_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: magstats_step
      base-folder: magstats_step

  prv_candidates_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: prv_candidates_step
      base-folder: prv_candidates_step

  reflector_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      base-folder: reflector_step
      step-name: reflector_step
      build-type: staging

  s3_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: s3_step
      base-folder: s3_step

  sorting_hat_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: sorting_hat_step
      base-folder: sorting_hat_step

  watchlist_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: watchlist_step
      base-folder: watchlist_step

  xmatch_step_staging:
    uses: ./.github/workflows/build-template.yaml
    needs: update_versions
    with:
      build-type: staging
      step-name: xmatch_step
      base-folder: xmatch_step
