name: Build staging Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Run alerce reflector step build staging
        uses: ./workflows_alerce-reflector-step/build_staging.yml

      - name: Run alerce alert archiving step
        uses: ./workflows_alert_archiving_step/build_staging.yml

        