name: Build_template
on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      base-folder:
        required: false
        type: string
        default: '.'
      username:
        required: true
        type: string
      password:
        required: true
        type: string
      file:
        required: false
        type: string
        default: 'Dockerfile'

    secrets:
      PUBLISH_IMAGE_TOKEN:
        required: true
jobs:
  build_and_push:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ inputs.username}}
          password: ${{ inputs.password }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./${{ inputs.file }}
          push: true
          tags: ${{ inputs.tags }}
