name: Build Production

on:
  release:
    types:
      - released

jobs:
    test_trigger:
        runs-on: ubuntu-latest
        steps:
            - name: print something
              run: "Builded Production"
