name: Check version is updated

on:
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check version is updated
        run: |
          VERSION_FILE=db_plugins/__init__.py
          perl -e '`git describe --tags --abbrev=0` =~ /(.+)\.(.+)\.(.+)/; ($of, $os, $ot) = ($1, $2, $3);'\
               -e '`cat '$VERSION_FILE'` =~ /__version__\s*=\s*['\''"](.+)\.(.+)\.(.+)['\''"]/;($nf, $ns, $nt) = ($1, $2, $3);'\
               -e '$nf < $of ? exit(1) : $nf > $of ? exit(0) : {};'\
               -e '$ns < $os ? exit(1) : $ns > $os ? exit(0) : {};'\
               -e '$nt <= $ot ? exit(1) : $nt > $ot ? exit(0) : {};'
