name: Tests_correction_step
on:
  pull_request:
    paths:
      - 'correction_step/**'
    branches:
      - main

jobs:
  lint:
    uses: alercebroker/workflow-templates/.github/workflows/lint.yml@main
    with:
      sources-folder: 'correction_step/correction'
  unittest:
    uses: alercebroker/workflow-templates/.github/workflows/poetry-tests.yml@main
    with:
      python-version: '3.10'
      sources-folder: 'correction_step/correction'
      test-folder: 'correction_step/tests/unittests'
  integration:
    uses: alercebroker/workflow-templates/.github/workflows/poetry-tests.yml@main
    with:
      python-version: '3.10'
      sources-folder: 'correction_step/correction'
      test-folder: 'correction_step/tests/integration'
      codecov-flags: ''  # Do not upload