name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'feature_step/**'
      - '!feature_step/README.md'

jobs:
  feature_step_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
      sources-folder: 'features'
      base-folder: 'feature_step'
  feature_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      python-version: '3.10'
      base-folder: 'feature_step'
      sources-folder: 'features'
      test-folder: 'tests/unittest'
      codecov-flags: ''  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  feature_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      python-version: '3.10'
      base-folder: 'feature_step'
      sources-folder: 'features/'
      test-folder: 'tests/integration'
      codecov-flags: ''  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  feature_step_build:
    uses: ./.github/workflows/build-template.yaml
    with:
      step-name: feature_step
      step-name-prefix: ""
      base-folder: feature_step
      build-context: "."
      git-ref: ${{ github.ref }}
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
