name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'feature_step/**'
      - '!feature_step/README.md'

jobs:
  feature_step_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
      sources-folder: 'features'
      base-folder: 'feature_step'
  feature_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      python-version: '3.10'
      base-folder: 'feature_step'
      sources-folder: 'features'
      test-folder: 'tests/unittest'
      codecov-flags: ''  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  feature_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      python-version: '3.10'
      base-folder: 'feature_step'
      sources-folder: 'features/'
      test-folder: 'tests/integration'
      codecov-flags: ''  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  build-feature-dagger:
    needs: update-packages-dagger
    uses: ./.github/workflows/template_build_with_dagger.yaml
    with:
        stage: staging
        extra-args: feature_step --dry-run
    secrets:
        GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
