name: integration_test

on:
  pull_request:
    paths:
      - 'xmatch_step/**'
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy Cython pytest-docker psycopg2
          if [ -f xmatch_step/requirements.txt ]; then pip install -r xmatch_step/requirements.txt; fi
      - name: Test with pytest
        run: |
          python -m pytest -x -s xmatch_step/tests/integration/
