name: Tests_prv_candidates_step

on:
  pull_request:
    paths:
      - 'prv_candidates_step/**'
    branches:
      - main

jobs:
  lint:
    uses: alercebroker/workflow-templates/.github/workflows/lint.yml@main
    with:
      sources-folder: "prv_candidates_step/prv_candidates_step"
  unittest:
    uses: alercebroker/workflow-templates/.github/workflows/pip-tests.yml@main
    with:
      python-version: "3.10"
      sources-folder: "prv_candidates_step/prv_candidates_step"
      test-folder: "prv_candidates_step/tests/unit"
      test-dependencies: "pytest pytest-cov pytest-mock"
      test-command: "python -m pytest -x prv_candidates_step/tests/unit --cov prv_candidates_step/prv_candidates_step --cov-report xml"
  integration:
    uses: alercebroker/workflow-templates/.github/workflows/pip-tests.yml@main
    with:
      python-version: "3.10"
      sources-folder: "prv_candidates_step/prv_candidates_step"
      test-folder: "prv_candidates_step/tests/integration"
      test-dependencies: "pytest pytest-docker pytest-mock"
      codecov-flags: "" # Do not upload
      test-command: "python -m pytest -x prv_candidates_step/tests/integration"
