name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'scribe/**'
      - '!scribe/README.md'

jobs:
  scribe_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      python-version: '3.9'
      sources-folder: 'mongo_scribe'
      base-folder: 'scribe'
      test-folder: 'tests/unittest'
      codecov-flags: ''  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  scribe_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      python-version: '3.9'
      sources-folder: 'mongo_scribe'
      base-folder: 'scribe'
      test-folder: 'tests/integration'
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  scribe_build:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: "scribe"
      build-context: "."
      step-name: "scribe"
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
