name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "scribe/**"
      - "!scribe/README.md"

jobs:
  scribe_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      python-version: "3.9"
      sources-folder: "mongo_scribe"
      base-folder: "scribe"
      test-folder: "tests/unittest"
      codecov-flags: "" # Do not upload
    secrets:
      GH_TOKEN: "${{ secrets.ADMIN_TOKEN }}"
  scribe_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      python-version: "3.9"
      sources-folder: "mongo_scribe"
      base-folder: "scribe"
      test-folder: "tests/integration"
    secrets:
      GH_TOKEN: "${{ secrets.ADMIN_TOKEN }}"

  build-scribe-dagger:
    uses: ./.github/workflows/template_build_with_dagger.yaml
    with:
      ref: ${{ github.ref }}
      stage: staging
      extra-args: scribe --dry-run
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
