name: Tests

on:
  pull_request:
    paths:
      - 'sorting_hat_step/**'
      - '!sorting_hat_step/doc'
      - '!sorting_hat_step/scripts'
    branches:
      - main

jobs:
  lint:
    uses: alercebroker/workflow-templates/.github/workflows/lint.yml@main
    with:
      sources-folder: 'sorting_hat_step/sorting_hat_step'
  unittest:
    uses: alercebroker/workflow-templates/.github/workflows/pip-tests.yml@main
    with:
      python-version: '3.8'
      sources-folder: 'sorting_hat_step/sorting_hat_step'
      test-folder: 'sorting_hat_step/tests/unittest'
      test-dependencies: "pytest pytest-cov 'moto[secretsmanager]'"
      pre-dependencies: 'numpy'
      test-command: 'python -m pytest -x sorting_hat_step/tests/unittest --cov sorting_hat_step/sorting_hat_step --cov-report xml'
  integration:
    uses: alercebroker/workflow-templates/.github/workflows/pip-tests.yml@main
    with:
      python-version: '3.8'
      sources-folder: 'sorting_hat_step/sorting_hat_step'
      test-folder: 'sorting_hat_step/tests/integration'
      test-dependencies: 'requests confluent_kafka numpy pymongo pytest pytest-docker pytest-cov'
      pre-dependencies: 'numpy'
      codecov-flags: ''  # Do not upload
      test-command: 'python -m pytest -x sorting_hat_step/tests/integration'
