name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'sorting_hat_step/**'
      - '!sorting_hat_step/README.md'

jobs:
  sorting_hat_step_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
      base-folder: 'sorting_hat_step'
      sources-folder: 'sorting_hat_step'
  sorting_hat_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'sorting_hat_step'
      python-version: '3.8'
      sources-folder: 'sorting_hat_step'
      test-folder: 'tests/unittest'
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  sorting_hat_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: 'sorting_hat_step'
      python-version: '3.8'
      sources-folder: 'sorting_hat_step'
      test-folder: 'tests/integration'
      codecov-flags: ''  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  sorting_hat_step_build:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: "sorting_hat_step"
      build-context: "."
      step-name: "sorting_hat_step"
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
