name: Lint and test
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
jobs:
  lint:
    uses: alercebroker/workflow-templates/.github/workflows/lint.yml@main
    with:
      sources-folder: 'lc_classification'
  unittest-ztf:
    uses: alercebroker/workflow-templates/.github/workflows/pip-tests.yml@main
    with:
      python-version: '3.8'
      requirements-file: 'requirements_ztf.txt'
      test-command: MODEL=ztf python -m pytest -x tests/unit --cov lc_classification --cov-report xml
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  integration-ztf:
    uses: alercebroker/workflow-templates/.github/workflows/pip-tests.yml@main
    with:
      python-version: '3.8'
      requirements-file: 'requirements_ztf.txt'
      test-dependencies: pytest pytest-docker
      test-command: MODEL=ztf python -m pytest -x tests/integration
      codecov-flags: ''  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  unittest-elasticc:
    uses: alercebroker/workflow-templates/.github/workflows/pip-tests.yml@main
    with:
      python-version: '3.8'
      requirements-file: 'requirements_elasticc.txt'
      test-command: MODEL=elasticc python -m pytest -x tests/unit --cov lc_classification --cov-report xml
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  integration-elasticc:
    uses: alercebroker/workflow-templates/.github/workflows/pip-tests.yml@main
    with:
      python-version: '3.8'
      requirements-file: 'requirements_elasticc.txt'
      test-dependencies: pytest pytest-docker
      test-command: MODEL=elasticc python -m pytest -x tests/integration
      codecov-flags: ''  # Do not upload
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'