name: Lint and test
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: alercebroker/workflow-templates/.github/workflows/lint.yml@main
    with:
      sources-folder: 'lc_classification'
  unittest-ztf:
    uses: alercebroker/workflow-templates/.github/workflows/pip-tests.yml@main
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      python-version: '3.8'
      requirements-file: 'requirements_ztf.txt'
      test-command: python -m pytest -x tests/unit --cov lc_classification --cov-report xml
  integration-ztf:
    uses: alercebroker/workflow-templates/.github/workflows/pip-tests.yml@main
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      python-version: '3.8'
      requirements-file: 'requirements_ztf.txt'
      test-dependencies: pytest pytest-docker
      test-command: python -m pytest -x tests/integration
      codecov-flags: ''  # Do not upload