name: Lint and test
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: alercebroker/workflow-templates/.github/workflows/lint.yml@main
    with:
      sources-folder: 'lc_classification'
  unittest:
    uses: alercebroker/workflow-templates/.github/workflows/poetry-tests.yml@main
    with:
      python-version: '3.8'
      sources-folder: 'lc_classification'
      test-folder: 'tests/unit'
  integration:
    uses: alercebroker/workflow-templates/.github/workflows/poetry-tests.yml@main
    with:
      python-version: '3.8'
      sources-folder: 'lc_classification'
      test-folder: 'tests/integration'
      codecov-flags: ''  # Do not upload