name: unittest

on:
  pull_request:
    paths:
      - 'alerce-reflector-step/**'
    branches:
      - main

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r alerce-reflector-step/requirements.txt
          pip install -r alerce-reflector-step/dev-requirements.txt
      - name: Test with pytest
        run: |
          coverage run --source cmirrormaker -m pytest -x alerce-reflector-step/tests/unittest
          coverage xml
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml