name: unittest

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download Model
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "alercebroker/stamp_classifier"
        file: "model.zip"
        token: ${{ secrets.READ_PACKAGE_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        unzip model.zip -d model
        pip install pytest coverage
        if [ -f model/requirements.txt ]; then pip install -r model/requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        coverage run --source earlyclassifier -m pytest -x -s tests/unittest/
        coverage xml
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
