name: unittest

on:
  pull_request:
    branches:
      - feature/*
      - feat/*
      - main

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage numpy fastavro
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        coverage run --source mongo_scribe -m pytest -x tests/unittest/
        coverage xml
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml