name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "watchlist_step/**"
      - "!watchlist_step/README.md"

jobs:
  watchlist_step_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
      sources-folder: "watchlist_step"
      base-folder: "watchlist_step"
  watchlist_step_unittest:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: "watchlist_step"
      python-version: "3.11"
      sources-folder: "watchlist_step"
      test-folder: "tests/unittest"
    secrets:
      GH_TOKEN: "${{ secrets.ADMIN_TOKEN }}"
  watchlist_step_integration:
    uses: ./.github/workflows/poetry-tests-template.yaml
    with:
      base-folder: "watchlist_step"
      python-version: "3.11"
      sources-folder: "watchlist_step"
      test-folder: "tests/integration"
      codecov-flags: "" # Do not upload
    secrets:
      GH_TOKEN: "${{ secrets.ADMIN_TOKEN }}"

  build-watchlist-dagger:
    uses: ./.github/workflows/template_build_with_dagger.yaml
    with:
      ref: ${{ github.ref }}
      stage: staging
      extra-args: watchlist_step --dry-run
    secrets:
      GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
