name: Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'watchlist_step/**'
      - '!watchlist_step/README.md'

jobs:
  watchlist_step_lint:
    uses: ./.github/workflows/lint-template.yaml
    with:
      sources-folder: 'watchlist_step'
      base-folder: 'watchlist_step'
  watchlist_step_unittest:
    uses: ./.github/workflows/pip-tests-template.yaml
    with:
      base-folder: 'watchlist_step'
      python-version: '3.8'
      sources-folder: 'watchlist_step'
      test-folder: 'tests/unittest'
      test-dependencies: 'pytest pytest-cov'
      test-command: 'python -m pytest -x tests/unittest --cov watchlist_step --cov-report xml'
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  watchlist_step_integration:
    uses: ./.github/workflows/pip-tests-template.yaml
    with:
      base-folder: 'watchlist_step'
      python-version: '3.9'
      sources-folder: 'watchlist_step'
      test-folder: 'tests/integration'
      test-dependencies: 'pytest==7.2.0 pytest-docker'
      codecov-flags: ''  # Do not upload
      test-command: 'python -m pytest -x tests/integration'
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  watchlist_step_build:
    uses: ./.github/workflows/build-template.yaml
    with:
      base-folder: "watchlist_step"
      build-context: "."
      step-name: "watchlist_step"
    secrets:
      GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
