name: tests_watchlist_step

on:
    pull_request:
      paths:
        - 'xmatch_step/**'
      branches:
        - main
jobs:
  lint:
    uses: alercebroker/workflow-templates/.github/workflows/lint.yml@main
    with:
      sources-folder: 'xmatch_step/xmatch_step/'
  unittest:
    uses: alercebroker/workflow-templates/.github/workflows/pip-tests.yml@main
    with:
      python-version: '3.7'
      sources-folder: 'xmatch_step/xmatch_step/'
      test-folder: 'xmatch_step/tests/unit'
      test-dependencies: 'pytest pytest-cov'
      requirements-file: 'xmatch_step/requirements.txt'
      test-command: 'python -m pytest -x xmatch_step/tests/unit --cov xmatch_step/xmatch_step/ --cov-report xml'
  integration:
    uses: alercebroker/workflow-templates/.github/workflows/pip-tests.yml@main
    with:
      python-version: '3.7'
      sources-folder: 'xmatch_step/xmatch_step/'
      test-folder: 'xmatch_step/tests/integration'
      test-dependencies: 'pytest pytest-docker numpy Cython psycopg2'
      requirements-file: 'xmatch_step/requirements.txt'
      codecov-flags: ''  # Do not upload
      test-command: 'python -m pytest -x xmatch_step/tests/integration'